---

stages:
  - build
  - lint
  - test
  - security

variables:
  IMAGE_TAG_DEV: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA.rag-chat.dev

build:
  stage: build
  tags:
    - docker-image
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -f docker/Dockerfile.dev -t "$IMAGE_TAG_DEV" .
    - docker push "$IMAGE_TAG_DEV"

check:
  stage: lint
  tags:
    - docker
  image: $IMAGE_TAG_DEV
  script:
    - cd src
    - sh bin/check.sh

check_types:
  stage: lint
  tags:
    - docker
  image: $IMAGE_TAG_DEV
  script:
    - cd src
    - sh bin/check_types.sh

test:
  stage: test
  tags:
    - docker
  image: $IMAGE_TAG_DEV
  script:
    - cd src
    - sh bin/test.sh

security:
  stage: security
  tags:
    - docker
  image: $IMAGE_TAG_DEV
  script:
    - cd src
    - sh bin/security.sh
